apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_HOST: {{ .Values.db.host | b64enc | quote }}
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
