apiVersion: v1
kind: Service
metadata:
  name: fantastic-app-service-alb
  namespace: {{ .Values.namespace }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: fantastic-app
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: LoadBalancer
